export const FONT_OPTIONS = {
  serif: {
    name: 'Serif',
    value: 'serif',
    fontFamily: 'Georgia, "Times New Roman", serif',
  },
  sans: {
    name: 'Sans Serif',
    value: 'sans',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  mono: {
    name: 'Monospace',
    value: 'mono',
    fontFamily: '"SF Mono", "Fira Code", "Fira Mono", Menlo, Consolas, monospace',
  },
  rounded: {
    name: 'Rounded',
    value: 'rounded',
    fontFamily: '"Nunito", "Varela Round", "Comic Neue", system-ui, sans-serif',
  },
} as const

export type FontOption = keyof typeof FONT_OPTIONS

export const COLOR_THEMES = {
  default: {
    name: 'Default',
    value: 'default',
    light: {
      background: '#ffffff',
      foreground: '#1a1a1a',
      card: '#ffffff',
      cardForeground: '#1a1a1a',
      primary: '#E86A4C',
      primaryForeground: '#ffffff',
      secondary: '#f5f5f5',
      secondaryForeground: '#1a1a1a',
      muted: '#f8f8f8',
      mutedForeground: '#888888',
      accent: '#f8f8f8',
      accentForeground: '#1a1a1a',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#f0f0f0',
      input: '#e5e5e5',
      ring: '#E86A4C',
    },
    dark: {
      background: '#0a0a0a',
      foreground: '#f5f5f5',
      card: '#0a0a0a',
      cardForeground: '#f5f5f5',
      primary: '#E86A4C',
      primaryForeground: '#ffffff',
      secondary: '#1a1a1a',
      secondaryForeground: '#f5f5f5',
      muted: '#1a1a1a',
      mutedForeground: '#888888',
      accent: '#1a1a1a',
      accentForeground: '#f5f5f5',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      border: '#262626',
      input: '#333333',
      ring: '#E86A4C',
    },
  },
  ocean: {
    name: 'Ocean',
    value: 'ocean',
    light: {
      background: '#f0f9ff',
      foreground: '#0c4a6e',
      card: '#ffffff',
      cardForeground: '#0c4a6e',
      primary: '#0284c7',
      primaryForeground: '#ffffff',
      secondary: '#e0f2fe',
      secondaryForeground: '#0369a1',
      muted: '#e0f2fe',
      mutedForeground: '#0369a1',
      accent: '#bae6fd',
      accentForeground: '#0c4a6e',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#bae6fd',
      input: '#bae6fd',
      ring: '#0284c7',
    },
    dark: {
      background: '#0c1929',
      foreground: '#e0f2fe',
      card: '#0f2942',
      cardForeground: '#e0f2fe',
      primary: '#38bdf8',
      primaryForeground: '#0c4a6e',
      secondary: '#164e63',
      secondaryForeground: '#e0f2fe',
      muted: '#164e63',
      mutedForeground: '#7dd3fc',
      accent: '#0369a1',
      accentForeground: '#e0f2fe',
      destructive: '#991b1b',
      destructiveForeground: '#ffffff',
      border: '#164e63',
      input: '#164e63',
      ring: '#38bdf8',
    },
  },
  forest: {
    name: 'Forest',
    value: 'forest',
    light: {
      background: '#f0fdf4',
      foreground: '#14532d',
      card: '#ffffff',
      cardForeground: '#14532d',
      primary: '#16a34a',
      primaryForeground: '#ffffff',
      secondary: '#dcfce7',
      secondaryForeground: '#166534',
      muted: '#dcfce7',
      mutedForeground: '#166534',
      accent: '#bbf7d0',
      accentForeground: '#14532d',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#bbf7d0',
      input: '#bbf7d0',
      ring: '#16a34a',
    },
    dark: {
      background: '#052e16',
      foreground: '#dcfce7',
      card: '#0d3d21',
      cardForeground: '#dcfce7',
      primary: '#4ade80',
      primaryForeground: '#14532d',
      secondary: '#166534',
      secondaryForeground: '#dcfce7',
      muted: '#166534',
      mutedForeground: '#86efac',
      accent: '#15803d',
      accentForeground: '#dcfce7',
      destructive: '#991b1b',
      destructiveForeground: '#ffffff',
      border: '#166534',
      input: '#166534',
      ring: '#4ade80',
    },
  },
  sunset: {
    name: 'Sunset',
    value: 'sunset',
    light: {
      background: '#fff7ed',
      foreground: '#7c2d12',
      card: '#ffffff',
      cardForeground: '#7c2d12',
      primary: '#ea580c',
      primaryForeground: '#ffffff',
      secondary: '#ffedd5',
      secondaryForeground: '#9a3412',
      muted: '#ffedd5',
      mutedForeground: '#9a3412',
      accent: '#fed7aa',
      accentForeground: '#7c2d12',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#fed7aa',
      input: '#fed7aa',
      ring: '#ea580c',
    },
    dark: {
      background: '#1c1410',
      foreground: '#ffedd5',
      card: '#2d1f17',
      cardForeground: '#ffedd5',
      primary: '#fb923c',
      primaryForeground: '#7c2d12',
      secondary: '#431407',
      secondaryForeground: '#ffedd5',
      muted: '#431407',
      mutedForeground: '#fdba74',
      accent: '#9a3412',
      accentForeground: '#ffedd5',
      destructive: '#991b1b',
      destructiveForeground: '#ffffff',
      border: '#431407',
      input: '#431407',
      ring: '#fb923c',
    },
  },
  lavender: {
    name: 'Lavender',
    value: 'lavender',
    light: {
      background: '#faf5ff',
      foreground: '#581c87',
      card: '#ffffff',
      cardForeground: '#581c87',
      primary: '#9333ea',
      primaryForeground: '#ffffff',
      secondary: '#f3e8ff',
      secondaryForeground: '#7e22ce',
      muted: '#f3e8ff',
      mutedForeground: '#7e22ce',
      accent: '#e9d5ff',
      accentForeground: '#581c87',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#e9d5ff',
      input: '#e9d5ff',
      ring: '#9333ea',
    },
    dark: {
      background: '#1a0f24',
      foreground: '#f3e8ff',
      card: '#2d1a3d',
      cardForeground: '#f3e8ff',
      primary: '#c084fc',
      primaryForeground: '#581c87',
      secondary: '#3b0764',
      secondaryForeground: '#f3e8ff',
      muted: '#3b0764',
      mutedForeground: '#d8b4fe',
      accent: '#7e22ce',
      accentForeground: '#f3e8ff',
      destructive: '#991b1b',
      destructiveForeground: '#ffffff',
      border: '#3b0764',
      input: '#3b0764',
      ring: '#c084fc',
    },
  },
  midnight: {
    name: 'Midnight',
    value: 'midnight',
    light: {
      background: '#f1f5f9',
      foreground: '#1e293b',
      card: '#ffffff',
      cardForeground: '#1e293b',
      primary: '#475569',
      primaryForeground: '#ffffff',
      secondary: '#e2e8f0',
      secondaryForeground: '#334155',
      muted: '#e2e8f0',
      mutedForeground: '#64748b',
      accent: '#cbd5e1',
      accentForeground: '#1e293b',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#cbd5e1',
      input: '#cbd5e1',
      ring: '#475569',
    },
    dark: {
      background: '#020617',
      foreground: '#f1f5f9',
      card: '#0f172a',
      cardForeground: '#f1f5f9',
      primary: '#94a3b8',
      primaryForeground: '#0f172a',
      secondary: '#1e293b',
      secondaryForeground: '#f1f5f9',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      accent: '#334155',
      accentForeground: '#f1f5f9',
      destructive: '#7f1d1d',
      destructiveForeground: '#ffffff',
      border: '#1e293b',
      input: '#1e293b',
      ring: '#94a3b8',
    },
  },
} as const

export type ColorTheme = keyof typeof COLOR_THEMES

export type ThemeMode = 'light' | 'dark' | 'system'

export const DEFAULT_FONT: FontOption = 'sans'
export const DEFAULT_COLOR_THEME: ColorTheme = 'default'
export const DEFAULT_MODE: ThemeMode = 'system'
